name: Lint and Format Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./sveltblazers

    - name: Run ESLint
      run: npm run lint
      working-directory: ./sveltblazers

    - name: Check format with Prettier
      run: npm run format
      working-directory: ./sveltblazers

