name: Lint and Format Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend

    - name: Run ESLint
      run: eslint 'src/**/*.ts'
      working-directory: ./frontend

    - name: Check format with Prettier
      run: prettier --check 'src/**/*.{ts,json,css,md}'
      working-directory: ./frontend

